### ISSUE TITLE
Direct back to filing application from "dead-end" pages

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-auth#105]
There are several "dead-end" pages that the user can reach. We need to add a method for redirecting the user back to the filing application. Discuss further with the team. 

- ~~accountUpdatedMessage=Your account has been updated.~~
- failedLogout=Logout failed
- sessionNotActiveMessage=Session not active.
- invalidCodeMessage=An error occurred, please login again through your application.

Edited to add:

- loginTimeout=You took too long to login.  Login process starting from beginning.
- expiredCodeMessage=Login timeout. Please login again.
- staleCodeMessage=This page is no longer valid, please go back to your application and login again

**Comment by keileyo** [comment]
Edit: The  "accountPasswordUpdatedMessage=Your password has been updated" already redirects back to the institutions page. I don't have a way to test whether "accountUpdatedMessage=Your account has been updated." also redirects already, but would prefer that it also redirect to the Instititions page.

**Comment by keileyo** [comment]
For session not active & generic error occurred, suggest a similar approach to 403 in [536](https://github.com/cfpb/hmda-platform-ui/issues/536)

"You must be logged in to access this page. Please **log in** and try again. If this problem persists, contact **HMDA help**."

sessionNotActiveMessage=Session not active.
invalidCodeMessage=An error occurred, please login again through your application.

**Comment by keileyo** [comment]
I suspect that "failedLogout=Logout failed" is very uncommon error, but the message should state the error and include a link back to the institutions page so that they can log out again. In the message below **log out** is a link back to the institutions. 

"Logout unsuccessful. Please **log out** and try again. If this problem persists, contact **HMDA Help**."

**Comment by awolfe76** [comment]
We _might_ need to include this template in our customizations - https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/error.ftl

**Comment by keileyo** [comment]
Per previous conversations, the action that we want the user to take is to try to log in again. 

For the timeout related errors:
- loginTimeout=You took too long to login.  Login process starting from beginning.
- expiredCodeMessage=Login timeout. Please login again.
- staleCodeMessage=This page is no longer valid, please go back to your application and login again
- sessionNotActiveMessage=Session not active.

"A timeout error occurred. "Please **log in** and try again. If this problem persists, contact HMDA help."

For the generic error:
- invalidCodeMessage=An error occurred, please login again through your application.

"An error occurred, please **log in** and try again. If this problem persists, contact HMDA help."

For the logout error, suggest sticking with my comment above. 



@designlanguage @awolfe76 thoughts?

**Comment by awolfe76** [comment]
Closing with #166.
