### ISSUE TITLE
Add language to registration page

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform-auth#117]
This will notify people who sign up for an account, that we will use the email address to send notifications.

"The provided email address will be used to notify you of any HMDA related technology updates." 

@awolfe76 @designlanguage we will need to find a spot for the language.

**Comment by awolfe76** [comment]
USWDS has a [possible solution](https://standards.usa.gov/components/form-controls/#section-/form-controls/05-date-input) ... using something like `<span class="usa-form-hint">The provided email address will be used to notify you of any HMDA related technology updates.</span>` below the `<label>` for the email input.
