### ISSUE TITLE
Use Keycloak's new export feature to generate HMDA realm config file

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform-auth#143]
We currently use Keycloak's awkward export-on-startup feature to dump the current realm config.  This was already confusing, but now that we've moved the Keycloak startup bits into the [`docker-entrypoint.sh`](https://github.com/cfpb/hmda-platform-auth/blob/master/keycloak/docker-entrypoint.sh#L66-L73), it's even more of a headache to make this work.

Keycloak has a new feature where you can export a realm's config right from the Admin UI...like it should have had from the beginning.  We should switch to using this type of export instead.  It will require a bit of testing, though, as it sounds like it is a subset of the overall config, and the export itself isn't formatted _exactly_ the same (different JSON pretty printing style :frowning_face:), so it's a little hard to do a direct diff against the current [`hmda-realm.json`](https://github.com/cfpb/hmda-platform-auth/blob/master/keycloak/import/hmda-realm.json).

**Comment by awolfe76** [comment]
I noticed this export the other day too. Seems like a good way to go.

**Comment by awolfe76** [comment]
@hkeeler - #146 closed this right?
