### ISSUE TITLE
Can see all institutions during registration

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-auth#150]
If you enter `name@` into the email field and then tab out you'll get a list of all the institutions returned from the API. The call that is made looks like `/public//institutions?domain=`. And the UI looks like

![all-fis](https://user-images.githubusercontent.com/2932572/29469848-10faf70e-8418-11e7-8c6f-69110fa24e19.png)

There are even more listed, all of them.

Two things:

1. We shouldn't make the call without a domain, the `@` shouldn't be enough.
2. Should the API work that way?

**Comment by hkeeler** [comment]
Whoa!  Good find @awolfe76!

 >We shouldn't make the call without a domain, the @ shouldn't be enough.

Agreed!  Any way we could get in a quick-fix nowish?

>Should the API work that way?

No.  @nickgrippin thoughts?

**Comment by awolfe76** [comment]
> Agreed! Any way we could get in a quick-fix nowish?

#151 😉

**Comment by hkeeler** [comment]
You're too quick @awolfe76!

Also, even though all those institutions get listed, the backend validation _should_ catch it, not allowing the user to be created.  Did you test that?

**Comment by awolfe76** [comment]
Good idea, I didn't but will right now.

**Comment by awolfe76** [comment]
I get an `Invalid email address provided.` error and we don't show the domains there which makes it _a little_ harder to fool. We should be good.

#151 helps too and stopping that on the endpoint will be even better.

**Comment by awolfe76** [comment]
@hkeeler @nickgrippin - I think we can close this one, but we'll need an issue open in the platform repo to update the endpoint, right?

**Comment by nickgrippin** [comment]
@awolfe76: created issue https://github.com/cfpb/hmda-platform/issues/1121
