### ISSUE TITLE
Switch Keycloak migration strategy to IGNORE_EXISTING

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform-auth#182]
Per http://www.keycloak.org/docs/latest/server_admin/topics/export-import.html

>#### -Dkeycloak.migration.strategy
>
>This property is used during import. It can be used to specify how to proceed if a realm with same name already exists in the database where you are going to import data. Possible values are:
>
>- IGNORE_EXISTING - Ignore importing if a realm of this name already exists.
>
>- OVERWRITE_EXISTING - Remove existing realm and import it again with new data from the JSON file. If you want to fully migrate one environment to another and ensure that the new environment will contain the same data as the old one, you can specify this.

We're using `OVERWRITE_EXISTING`.  Our previous assumption was that this would just update a realm's config for a given realm, not a drop/create.  This works great for development, but not-so-much for other environments.

For now, let's just switch to `IGNORE_EXISTING`.  We'll have a follow-up issue to come up with a solution for pushing config changes to existing realms.

**Comment by hkeeler** [comment]
The file that sets this up is https://github.com/cfpb/hmda-platform-auth/blob/master/keycloak/docker-entrypoint.sh.

**Comment by hkeeler** [comment]
To check that users have survived a container restart, do the following query against the `keycloak` database on `keycloak_db`.
```sql
SELECT * FROM user_entity;
```

**Comment by kgudel** [comment]
Setting:
```json
"cmd": "sed -i 's/-Dkeycloak.migration.strategy=OVERWRITE_EXISTING/-Dkeycloak.migration.strategy=IGNORE_EXISTING/' docker-entrypoint.sh && ./docker-entrypoint.sh"
```
in the marathon.json for keycloak will solve this temporarily.

I tested this on release in `HMDA3` and accounts survive restarts of keycloak. This change is still live in `HMDA3` if you want to do additional testing.
