### ISSUE TITLE
Expired Account Registration Links - Update Message

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-auth#191]
We previously did some work on directing users on what to do if the link they receive has expired in #102, and the UI message that we implemented is documented in #140. 

However, it appears that the actual message users receive when they click a link that has expired is the one that they are intended to receive if the link has already been visited in #147.

Ideally, we are able to implement #140 for account verification links that are expired, but if both scenarios (expired link and stale link that has already been verified) have to direct to the same end message, we will need to update the messaging on that page to tell users with an expired link that attempting to log in again will send them a new account verification email. 

@awolfe76 @hkeeler @wpears thoughts?

**Comment by hkeeler** [comment]
I'm pretty sure at this point that Keycloak uses the same error [`staleEmailVerificationLink`](https://github.com/cfpb/hmda-platform-auth/blob/5e963f3ce6476886c4fb1f84ccd610ca48516923/keycloak/themes/hmda/login/messages/messages_en.properties#L29) messages for both an expired link **and** an already-clicked link.  I've been trying to dig into the underlying Keycloak code, and it _seems_ to point in that direction.

Additionally, [the default value for `staleEmailVerificationLink`](https://github.com/keycloak/keycloak/blob/f80811a065ef79b0a9385233be6a84b252d00ce9/themes/src/main/resources/theme/base/login/messages/messages_en.properties#L223) is:

>The link you clicked is a old stale link and is no longer valid.  Maybe you have already verified your email?

This message is a little awkward, and sounds kinda like they're trying to have it both ways.

I'll make some tweaks to my local setup that should let us confirm/deny whether this is true.  I'll report back when I know more.

**Comment by hkeeler** [comment]
I think things have changed a bit with the upgrade to Keycloak 3.4.0.  I've tested the following scenarios, following the links in the confirmation emails:

1. Self registration
    1. Link expired - _Action expired. Please start again._ on login page.
    1. Link already selected - _You are already logged in._
1. Admin registration
    1. Link expired - _Action expired._ on error screen w/ _Login_ button.
    1. Link already selected - No difference from initially selecting link
1. Self password reset
    1. Link expired - _Action expired. Please start again._ on login page.
    1. Link already selected - No difference from initially selecting link
1. Admin password reset
    1. Link expired - _Action expired. Please start again._ on login page.
    1. Link already selected - No difference from initially selecting link

So, the error messages seem to have moved over to the even more generic [`expiredAction`](https://github.com/keycloak/keycloak/blob/2a2e6c839b74409c56782c3bd919b465f664cb7b/themes/src/main/resources/theme/base/login/messages/messages_en.properties#L133-L135) messages.

Also, I have come across that _Action expired.  Please continue with login now._ message too, I believe on the Keycloak error page with the _Login_ button.  I'm not sure the exact scenario how I got that.  I'll try to pin that down too.

**Comment by keileyo** [comment]
I was able to test registration once. When I let the link expire, it took me right back to the "create an account" page upon clicking the link, but i did not receive a message of any kind letting me know that i needed to create an account again. I will test further when the dev env is available. 

 Based on your comments above, I appreciate that the expired link & link already selected should produce different results. In general, the actions are fine, I think we just tweak the messaging to be more clear.  For example:

1.  Self registration
Link Expired: The verification link is expired. Please create your account again and verify your account registration within 60 minutes. 
Link already selected: This link has already been visited. Please login. 

I think for the most part, we are staying away from admin registration and entirely away from admin password reset. The most common use case for admin registration is associating a second institution w/ a known account, but our process thus far has been to remove accounts & ask users to register again once all institutions for the specified domain is available. This is preferable because it doesn't require us to associate the account and send the verification email at a time when we believe the user will click the link within 60 minutes. The user can re-register on their own time.

**Comment by hkeeler** [comment]
Closed by #203.
