### ISSUE TITLE
Remove echo-api and oidc-test

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform-auth#20]
Once we're happy with `hmda-platform-ui`'s OIDC setup, let's remove the `echo-api` and `oidc-client` test apps.  This will include:

1. Removing the `echo-api` and `oidc-client` directories.
1. Replacing `http://echo:5000` as the default response in [`000-default.conf`](https://github.com/cfpb/hmda-platform-auth/blob/master/auth-proxy/000-default.conf).  We _could_ tie this in with https://github.com/cfpb/hmda-platform-auth/issues/17 and use the base `/` as the _status_ endpoint.
1. Remove all references to `echo-api` and `oidc-client` from `README.md`.

**Comment by awolfe76** [comment]
Closed by #22
