### ISSUE TITLE
Platform asking for a one-time code during log-in

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform-auth#212]
We received the following screenshot from an institution trying to log into the platform

![image](https://user-images.githubusercontent.com/32906749/35122178-d995fc2e-fc6b-11e7-9d66-9da89e792a2b.png)

**Comment by hkeeler** [comment]
This was fixed in prod via the the keycloak Admin console.  This will be fixed in all dev envs via #220.
