### ISSUE TITLE
Error message during account creation if user hits enter after typing email address

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform-auth#214]
We've seen a few example of users receiving the below error message during account registration. We can replicate it by typing the email address and hitting enter, rather than just typing the email address and waiting for the institution name to load. This is a recognized domain:

![image](https://user-images.githubusercontent.com/32906749/35645872-629e9128-069b-11e8-8fe1-55d7332c7efa.png)

**Comment by awolfe76** [comment]
Thanks, @colleenms. The "enter/return" key submits the form, so this is expected.

Have they been unable to register because of this? Or have they figured it out?

--- 

_If we need to do something_ there are a few things we could do to help here:

1. don't allow the "enter/return" key to submit the form,
1. disable submission and do more in-line validation to make sure all fields have data (at the very least), or
1. think of a better workflow around getting the list of institutions. 

@designlanguage

**Comment by wpears** [comment]
I think 3 is the best choice here, I think we should widen the user actions that trigger the request (if valid data exists).

This particular case would be fixed by attempting to fetch institutions on load (as submission will then trigger a load of the new page).

**Comment by wpears** [comment]
Work here will also fix the unreported-but-extant bug that prevents institution search from being triggered when selecting your email from autofill.

**Comment by awolfe76** [comment]
> This particular case would be fixed by attempting to fetch institutions on load (as submission will then trigger a load of the new page).

👍 

> Work here will also fix the unreported-but-extant bug that prevents institution search from being triggered when selecting your email from autofill.

It does work `onBlur` but yes, if we can do it earlier that would be good.

---

Also, we used to have some help text here that let them know they would need to select an institution. We removed it a while back but looking at this problem it seems like that would be useful.

We mention "The provided email address will be used to notify you of any HMDA related technology updates" but don't say anything about it being required to select an institution ... there's no immediate way of knowing that another form field actually exists. A simple message may help with this. 

Thoughts?

**Comment by colleenms** [comment]
Thanks @awolfe76, makes complete sense. I agree, maybe we can change to "The provided email address will be used to identify your financial institution(s) and notify you of ..."

It also may help to change the error message to "Please select the financial institution(s)..." , so the user knows it should appear in a list rather than needing to type it in a separate data field.

@keileyo

**Comment by designlanguage** [comment]
I wonder if people aren't seeing the password field (just the requirements), so they think they are finished with the form. 

The revised messaging sounds good to me, but in addition to that, I also like @awolfe76 's first idea of not allowing return/enter to submit the form. What if return acted like tabbing to the next field? Would that be problematic?

**Comment by awolfe76** [comment]
What I think is happening is that they just happen to hit the "enter/return" key, which submits the form. This is common and we shouldn't change that, it wouldn't be good for accessibility reasons. Sorry for making that suggestion.

We could disable the submission until all fields have values, the 2nd option. (I'm a little worried about doing other checks because we'd have to match Keycloaks back-end validation exactly.)

Doing that, along with what @wpears suggested about the "on load" and adding a message would help.

**Comment by keileyo** [comment]
How about the fourth bullet in the error message be revised. 

"Please provide your email address and choose the financial institution(s) for which you will be filing from the list that populates under your email address." 

I'm on the fence about whether we should explicitly include "do not press enter" @colleenms thoughts?

**Comment by awolfe76** [comment]
I think we're ok to update the error message returned when no institution has been selected.

I would vote against any "do not press enter" message (see [this comment](https://github.com/cfpb/hmda-platform-auth/issues/214#issuecomment-362370847)]. Basically, that's a very common thing on forms ... and I've never seen that anywhere else.

**Comment by colleenms** [comment]
Agree with @awolfe76, especially since users have this issue infrequently. My suggestion for the text above the email field:

"The provided email address will be used to identify your financial institution(s) and notify you of any HMDA related technology updates."

**Comment by keileyo** [comment]
@awolfe76 @colleenms sounds good to me re: the enter stuff (it seemed weird to include). I'm good with the message that i originally proposed.

**Comment by wpears** [comment]
Handled by #216, if we want to do anything like preventing form submitting during institutions fetch or moving the password rules so more of the form is on the screen at the same time, we can create more issues.
