### ISSUE TITLE
Improve Select2 HTML snippet code on account registration page

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform-auth#24]
As discussed on https://github.com/cfpb/hmda-platform-auth/pull/23#pullrequestreview-9616346, the HTML snippet used for populating the select2 dropdown on the Keycloak registration page is a bit unwieldy.  Let's see if we can come up with a cleaner solution.

**Comment by awolfe76** [comment]
A possible solution to have for later - http://select2.github.io/select2/#templating

**Comment by wpears** [comment]
I'd say this is pretty low priority, unless/until we find ourselves editing the code in question.

**Comment by hkeeler** [comment]
We are no longer using Select2.  Closing.
