### ISSUE TITLE
Implement institutions/<id> for institutions API

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-auth#25]
As noted in https://github.com/cfpb/hmda-platform-auth/pull/23, this endpoint needs to be fixed/implemented (the `inst_by_id` dict needs to be initialized, etc.)

Once this is done, the endpoint can also be used in the `getInstitution` method of the form action.

**Comment by hkeeler** [comment]
This is no longer necessary.  The backend does a lookup by email domain, and that is sufficient for institution validation.
