### ISSUE TITLE
Review all of Keycloak error messages

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform-auth#39]
Keycloak has many error messages, most of which are pretty easy to override via the `messages_en.properties` added as part of PR #38.  Let's review all of them, and see if we need to update the defaults.

There are likely other error messages that come from Keycloak's backend code.  These are likely a bit trickier to change, but probably not impossible.  Let's walk through the app and see if any of these need to be modified as well.

There are some specific error messages issues discussed on #37 that would should take into account as part of the review.

**Comment by hkeeler** [comment]
Let's make sure we take username vs. email inconsistencies into account.  See #53.

**Comment by hkeeler** [comment]
For reference, Keycloak has a base set of messages, which can be overridden per theme.  We are currently overridding the `login` theme, though we should also check out the `email` theme.  We could override it too if we think the email-related messages need to be updated:

* [`base/login`](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/messages/messages_en.properties)
    * [`hmda/login` (overrides `base/login`)](https://github.com/cfpb/hmda-platform-auth/blob/master/keycloak/themes/hmda/login/messages/messages_en.properties)
* [`base/email`](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/email/messages/messages_en.properties)

**Comment by hkeeler** [comment]
@lesgou and @keileyo, can we close this out?  Are all the remaining Keycloak error messages in place or ticketed?  If not, do you want to keep this open as a reminder that there's still more to do?

**Comment by keileyo** [comment]
Closing & opening more specific tickets.
