### ISSUE TITLE
Should support email have a message body?

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform-auth#43]
As mentioned on https://github.com/cfpb/hmda-platform-auth/pull/38#issuecomment-266104430, the support email `mailto:` link only provides the `To:` and `Subject:`.  Do we want to provide a message body as well?  This could be a template to help nudge the user into providing the appropriate information to help resolve their problem.

If _yes_, what content should be in this email message?

**Comment by designlanguage** [comment]
@hkeeler - What information would be needed to help them resolve their problem? Is there a standard list that would be helpful to receive up front?

**Comment by hkeeler** [comment]
At today's planning meeting we decided this was not necessary.  Closing.
