### ISSUE TITLE
Fix <script> tag in Keycloak "Create an account" page's title

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform-auth#50]
For some reason, a <script> tag is being added to the title of the _Create an account_ page.  I haven't looked into _why_, but I suspect it will be an easy fix.

<img width="919" alt="screen shot 2017-01-04 at 2 28 28 pm" src="https://cloud.githubusercontent.com/assets/4269085/21656074/90017630-d28a-11e6-95e5-d4ba299e2071.png">

**Comment by awolfe76** [comment]
Wow, neat! 😃 

Want me to take a look?
