### ISSUE TITLE
Friendly URLs

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-auth#51]
Right now the URL for the login page is something like `/auth/realms/hmda/protocol/openid-connect/auth?client_id=hmda-api&redirect_uri=http%3A%2F%2F192.168.99.100%2Foidc-callback&response_type=id_token%20token&scope=openid%20profile&state=95d438f06c1242ec96cc03406bf2053d&nonce=2debe8e223e7473a87802cfa575cca5a`.

The URL for the registration page is something like `/auth/realms/hmda/login-actions/registration?code=dXoAF0rFrXtnGreHuGQBhY_8VDb0Jdzqc4n-5jPte4k.7f285739-be87-48e8-910f-82518ae66350`.

Can these be made friendly, to something like `/login` and `/register`?

**Comment by hkeeler** [comment]
The short answer is **_probably not_**.  Keycloak _really_ likes it paths they way they are.  I did attempt to just take off the leading `/auth` when reverse proxying to Keycloak, and I couldn't even make that work.  I found some discussions with other folks having similar issues.

I'll leave this open for now, and try to come back with a more concrete answer.

**Comment by hkeeler** [comment]
Also, the registration `code` and `token` params are definitely required, so you're not going to get rid of that.

**Comment by awolfe76** [comment]
> I'll leave this open for now, and try to come back with a more concrete answer.

👍

**Comment by hkeeler** [comment]
I am having to put a reverse proxy in front of Keycloak as part of #78.  Once I have that working, it'll be easy to test out whether or not we can make the URL a little nicer.

**Comment by alexruzenhack** [comment]
@hkeeler, did you succeed to implement friend url through reverse proxy? I tried through apache mod_rewrite and nothing.

**Comment by hkeeler** [comment]
The URL for our keycloak site are well established at this point.  We definitely won't be changing them.  Closing.
