### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-auth#52]
Remove or update the `Error Status` part of the alerts, found [here](https://github.com/cfpb/hmda-platform-auth/blob/90666320cbd0c9f8eb84fbaa8daf63bc44196147/keycloak/themes/hmda/login/template.ftl#L65). It's not very friendly. The messages like `Invalid username or password.` might be enough in this case.

**Comment by hkeeler** [comment]
The warning and error message blocks feel awkward to me too.  I think just removing the word _Status_ and capitalizing _Error_ and _Warning_ would be a nice start. :)  I don't think we should remove the `message.type` all together, though.  Without that, all you have is the background color to let you know it is a warning vs. error.

I think it's also awkward when there is more than one error message in the error block.  When the messages get long and wrap the next line, it is hard to tell if it a new message or a continuation.  The junky bit here is that `message.summary` (what get's printed into the box) is a hardcode concatenation of error messages with `<br>`s between them (see: [`MessageBean.addSummaryLine`](https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/theme/beans/MessageBean.java#L37-L43)).  Why not make the underlying list of errors availabe?...I really don't know.

The other option here is to use their [`MessagesPerFieldBean`](https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/theme/beans/MessagesPerFieldBean.java), which gives you message when you pass in a given field name.  This is not really useable for the top-level message block, only if we want to put the errors next to the form fields themselves.

Thoughts?  Happy to chat about this more.  I dug into all this a while back.

**Comment by awolfe76** [comment]
> I don't think we should remove the message.type all together, though. Without that, all you have is the background color to let you know it is a warning vs. error.

I thought about this and I don't think it's a problem. At the login and registration levels, they all come back as errors. Adding the "Error" doesn't provide any benefit.

> The other option here is to use their MessagesPerFieldBean, which gives you message when you pass in a given field name. This is not really useable for the top-level message block, only if we want to put the errors next to the form fields themselves.

I like this. Can we do both? We shouldn't take away the top level message(s) but adding this per field would be nice.

> is a hardcode concatenation of error messages with <br>s between them (see: MessageBean.addSummaryLine).

Would it be a bad idea to customize that into a list? We'd have a lot more flexibility that way.
