### ISSUE TITLE
Timeout? - took to long to login

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-auth#54]
If you leave the application sit for a while on the login page and then try to login, you get a message saying `took to long to login`. 

Can we remove that and just make the form work?

**Comment by hkeeler** [comment]
Nope.  In order for the OIDC handshake to work, the code passed to the login screen has to be kept around for subsequent phases of the handshake, and that code has to have a timeout.

We could increase the timeout if it seems to short now.

**Comment by awolfe76** [comment]
> We could increase the timeout if it seems to short now.

What is it set to now? I do think it should be increased.

**Comment by awolfe76** [comment]
@hkeeler - can you point me to this setting so I can take a look?

**Comment by awolfe76** [comment]
@hkeeler - I think #146 is good for this, yeah?
