### ISSUE TITLE
Refresh error

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-auth#55]
If you refresh on either the forgot password or registration page you'll see this error - `An error occurred, please login again through your application.`

This happens on the login page IF you go to one of the other pages, come back to the login page, and hit refresh.

Can we have refresh ... just refresh? 😄

**Comment by hkeeler** [comment]
I agree.  I'm not a fan of this either.  However, I don't think we'll have much luck trying to override whatever Keycloak session/OIDC handling is going on there.  Even if we could, there are likely security implications with doing so.  I think our best chance would be to change that page to a redirect back to our app, which would then redirect back to login if the user is not authenticated.

**Comment by awolfe76** [comment]
> I think our best chance would be to change that page to a redirect back to our app, which would then redirect back to login if the user is not authenticated.

👍

**Comment by awolfe76** [comment]
Refresh works in production! Closing.
