### ISSUE TITLE
Checkboxes vs Select2

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-auth#56]
Because we're going to be returning institutions based on domain name (issue coming) should we only render the results are checkboxes (instead of using the select2 with type ahead) and then only register the user with what they've selected?

If so, and if only one institution is returned based on the domain we should default the one result to be "checked".

**Comment by hkeeler** [comment]
Checkboxes feel awkward to me.  I think it'd be weird to have a variable number of checkboxes pop up based on the email domain.  I think users are more used to a variable-length list  ...and we'd have to build that custom UI widgetry.  That said, I'd be interested to see it if you wanted to do a mockup.

I do like the idea of auto-selecting the institution if there is an exact one-to-one match, whichever UI widget we decide to go with.

**Comment by awolfe76** [comment]
I don't think the variable-length part would be the issue here, it's more about how the number of options that might be possible. If that number is large, then yes, the select is the better option. I'm assuming, maybe incorrectly, that the number of options would be pretty small per domain which would make checkboxes a better choice here.

But, it is fine for now. We can leave this open and think about it more once we have real data to see what's happening.

I created #57 for the default if only one institution is returned.

**Comment by hkeeler** [comment]
Closed by PR #67
