### ISSUE TITLE
Populate institution checkboxes appropriately on registration failure

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform-auth#71]
Currently when an account registration attempt fails (say, password mismatch), most of the non-error-fields remain populated (first name, last name, email).  However, the set of institution checkboxes is always cleared out on failure.  Seems like we should make this consistent.

In order to implement this, the Keycloak backend will have to return the comma-separated list of valid institution IDs, and the frontend will have to parse that, and check the corresponding checkboxes.

This is not a high priority.  For now, users will just have to re-select the appropriate institutions on a fail.

**Comment by awolfe76** [comment]
This is working as it should, the selected institution is staying "checked".
